#!/bin/sh
mknod -m 622 /dev/tty0 c 4 0
exec </dev/tty0 >/dev/tty0 2>&1
# better-initramfs project
# https://bitbucket.org/piotrkarbowski/better-initramfs
# Copyright (c) 2010-2018, Piotr Karbowski <piotr.karbowski@gmail.com>
# All rights reserved.

# Load functions.
. /functions.sh
run_hooks init
# Prepare dirs
run dodir /dev /newroot /sbin /proc /sys /etc /var/log /var/run /run /run/cryptsetup /ps4hdd
for d in /lib /usr/lib; do
   # ! -e && ! -h: also skip broken symlinks
   if [ -d "${d}" ] && [ ! -e "${d}64" ] && [ ! -h "${d}64" ]; then
      run ln -s "${d}" "${d}64"
   fi
done
unset -v d
# Basic /dev content, we need it as fast as possible.
[ ! -e /dev/console ]  && run mknod /dev/console c 5 1
[ ! -e /dev/null ]     && run mknod /dev/null c 1 3
[ ! -e /dev/tty ]      && run mknod /dev/tty c 5 0
[ ! -e /dev/urandom ]  && run mknod /dev/urandom c 1 9
[ ! -e /dev/random ]   && run mknod /dev/random c 1 8
[ ! -e /dev/zero ]     && run mknod /dev/zero c 1 5
# Save IFS so we can easly restore it if we ever change it.
readonly default_ifs="${IFS}"
# Basic
kernelver="$(uname -r)"
ver="$(cat /VERSION)"
einfo "better-initramfs ${ver}. Linux kernel ${kernelver}.\n"
echo -e "\nWelcome to ${ver}. Linux kernel ${kernelver}.\n" > /etc/motd
emount /proc /sys
# Set the Clock from Orbis
time_from_cmdline="$(grep -o 'time=[0-9]*' /proc/cmdline | cut -d= -f2)"
if [ -n "$time_from_cmdline" ]; then
    date -s "@$time_from_cmdline"
fi
# Disable kernel messages from popping onto the screen
echo 0 > /proc/sys/kernel/printk
InitializeBusybox
emount /dev
#echo "off" > /sys/class/drm/card0-HDMI-A-1/status
#cat /lib/firmware/edid/my_edid.bin > /sys/kernel/debug/dri/0/HDMI-A-1/edid_override
run_hooks early
#SetupNetwork
#use sshd && setup_sshd
loadkeymap
use rootdelay rootdelay
use bcache register_bcache_devices
use softraid InitializeSoftwareRaid && use bcache register_bcache_devices
use lvm InitializeLVM && use bcache register_bcache_devices
use luks InitializeLUKS && use lvm InitializeLVM && use bcache register_bcache_devices
# slow drives need here more sleeptime maybe?
sleep 8
#echo "on" > /sys/class/drm/card0-HDMI-A-1/status
populate_dev_disk_by_label_and_uuid
res=$(dmesg | grep 0x9920)
if [ "$res" == "" ]; then
echo -e "\e[31m\e[1m>\e[34m\e[1m>\e[31m\e[1m> \e[39m\e[0m\e[32m\e[1mPS4 Belize / Baikal\e[39m\e[0m internal drive mounted"
cryptsetup -d /key/eap_hdd_key.bin --cipher aes-xts-plain64 -s 256 --offset 0 --skip 111669149696 create ps4hdd /dev/sd?27
mount -t ufs -o ufstype=ufs2 /dev/mapper/ps4hdd /ps4hdd
chmod -R a+rwX /ps4hdd
else
echo -e "\e[31m\e[1m>\e[34m\e[1m>\e[31m\e[1m> \e[39m\e[0m\e[32m\e[1mPS4 Aeolia\e[39m\e[0m internal drive mounted"
cryptsetup -d /key/eap_hdd_key.bin --cipher aes-xts-plain64 -s 256 --offset 0 create ps4hdd /dev/sd?27
mount -t ufs -o ufstype=ufs2 /dev/mapper/ps4hdd /ps4hdd
chmod -R a+rwX /ps4hdd
fi
CONFIG_FILE="/ps4hdd/data/linux/boot/initramfs.ini"
show_menu() {
  echo ""
  echo "========= Playstation Boot-Menü ========="
  echo "[1] Default Boot"
  echo "[2] Installation"
  echo "[3] Rescue-System (Shell)"
  echo "[q] Reboot to Orbis OS"
  echo "======================================="
  echo ""

  if [ -f "$CONFIG_FILE" ]; then
    echo "Please make your selection (1-3)..."
    echo "Automatic boot in 3 seconds:"

    SECONDS_LEFT=3
    INPUT=""

    while [ $SECONDS_LEFT -gt 0 ]; do
      echo -n "$SECONDS_LEFT... "
      read -t 1 -n 1 INPUT
      if [ $? -eq 0 ]; then
        echo ""
        break
      fi
      SECONDS_LEFT=$((SECONDS_LEFT - 1))
    done

    if [ -z "$INPUT" ]; then
      INPUT=1
    fi
  else
    echo "No Autoboot start configuration found!"
    echo -n "Please make your selection (1-3): "
    read -n 1 INPUT
    echo ""
  fi

  case "$INPUT" in
    1)
      echo ">> Opens the parition selection menu.."

SAVEFILE="/ps4hdd/data/linux/boot/initramfs.ini"
MOUNTPOINT="/newroot"
LABEL_PREFIX="ps4"
TIMEOUT=5
IMG_DIR="/ps4hdd/data/linux"
LOOPDEV="/dev/loop0"

human_readable_size() {
    size="$1"
    if [ "$size" -ge 1073741824 ]; then
        echo "$((size / 1073741824))G"
    elif [ "$size" -ge 1048576 ]; then
        echo "$((size / 1048576))M"
    elif [ "$size" -ge 1024 ]; then
        echo "$((size / 1024))K"
    else
        echo "${size}B"
    fi
}

[ -b "$LOOPDEV" ] || mknod "$LOOPDEV" b 7 0

# Pseudo-Dateisysteme mounten
#mount -t proc none /proc
#mount -t sysfs none /sys
#mount -t devtmpfs none /dev

while true; do
    PS4_PARTS=$(ls /dev/disk/by-label/ 2>/dev/null | grep "^$LABEL_PREFIX")
    IMG_PARTS=$(ls "$IMG_DIR"/*.img 2>/dev/null | sed "s|$IMG_DIR/||")

    if [ -z "$PS4_PARTS" ] && [ -z "$IMG_PARTS" ]; then
        echo "No partitions or images found."
        sleep 3
        continue
    fi

    if [ -f "$SAVEFILE" ]; then
        SEL=$(cat "$SAVEFILE")
        if [ -e "/dev/disk/by-label/$SEL" ]; then
            echo "booting in $TIMEOUT seconds with partition: $SEL"
            echo "press Enter for Menu, the automatic boot will be stopped ..."
            read -t $TIMEOUT dummy
            if [ $? -ne 0 ]; then
                echo "mounting /dev/disk/by-label/$SEL → $MOUNTPOINT"
                mount "/dev/disk/by-label/$SEL" "$MOUNTPOINT" && break
                echo "Mounting failed."
                sleep 2
                continue
            fi
        elif [ -f "$IMG_DIR/$SEL" ]; then
            echo "booting in $TIMEOUT seconds with partition: $SEL"
            echo "press Enter for Menu, the automatic boot will be stopped..."
            read -t $TIMEOUT dummy
            if [ $? -ne 0 ]; then
                echo "mounting $IMG_DIR/$SEL → $MOUNTPOINT (loop)"
                losetup "$LOOPDEV" "$IMG_DIR/$SEL" && mount "$LOOPDEV" "$MOUNTPOINT" && break
                echo "Mounting failed.. Loop trennen."
                losetup -d "$LOOPDEV" 2>/dev/null
                sleep 2
                continue
            fi
        fi
    fi


    echo "Please select a [External]partition or an [internal]image:"
    i=1

    for part in $PS4_PARTS; do
        DEVICE="/dev/disk/by-label/$part"
        SIZE_BYTES=$(blockdev --getsize64 "$DEVICE" 2>/dev/null)
        if [ -n "$SIZE_BYTES" ]; then
            SIZE_HUMAN=$(human_readable_size "$SIZE_BYTES")
        else
            SIZE_HUMAN="unbekannt"
        fi
        echo "$i) [EXT] $part  ($SIZE_HUMAN)"
        eval "opt_$i=part:$part"
        i=$((i + 1))
    done

    for img in $IMG_PARTS; do
        SIZE_BYTES=$(stat -c%s "$IMG_DIR/$img" 2>/dev/null)
        if [ -n "$SIZE_BYTES" ]; then
            SIZE_HUMAN=$(human_readable_size "$SIZE_BYTES")
        else
            SIZE_HUMAN="unbekannt"
        fi
        echo "$i) [INT] $img  ($SIZE_HUMAN)"
        eval "opt_$i=img:$img"
        i=$((i + 1))
    done

    echo -n "Selection [1]: "
    read choice
    choice=${choice:-1}

    eval "SEL_LINE=\$opt_$choice"
    TYPE=$(echo "$SEL_LINE" | cut -d: -f1)
    VALUE=$(echo "$SEL_LINE" | cut -d: -f2-)

    if [ "$TYPE" = "part" ]; then
        echo "$VALUE" > "$SAVEFILE"
        echo "Mounting /dev/disk/by-label/$VALUE → $MOUNTPOINT"
        mount "/dev/disk/by-label/$VALUE" "$MOUNTPOINT" && break
        echo "Mount failed."
        sleep 2
    elif [ "$TYPE" = "img" ]; then
        echo "$VALUE" > "$SAVEFILE"
        echo "Mounting $IMG_DIR/$VALUE → $MOUNTPOINT "
        losetup "$LOOPDEV" "$IMG_DIR/$VALUE" && mount "$LOOPDEV" "$MOUNTPOINT" && break
        echo "Mount failed."
        losetup -d "$LOOPDEV" 2>/dev/null
        sleep 2
    else
        echo "Invalid selection."
        sleep 2
    fi
done

echo "Copy PS4 files to $MOUNTPOINT ..."
if [ -f /key/eap_hdd_key.bin ]; then
    cp /key/eap_hdd_key.bin "$MOUNTPOINT/"
fi
mkdir -p "$MOUNTPOINT/lib/firmware"
cp -R /lib/firmware/amdgpu "$MOUNTPOINT/lib/firmware/" 2>/dev/null
mkdir -p "$MOUNTPOINT/lib/firmware/edid"
cp /lib/firmware/edid/my_edid.bin "$MOUNTPOINT/lib/firmware/edid/" 2>/dev/null
mkdir -p "$MOUNTPOINT/ps4hdd"
mount --rbind /ps4hdd "$MOUNTPOINT/ps4hdd"
echo "booting switch_root to $MOUNTPOINT ..."
exec switch_root "$MOUNTPOINT" /sbin/init
echo "switch_root failed! press Enter"
exec sh
      ;;
    2)
      echo ">> Open Installationmenu..."
      /install.sh
      ;;
    3)
      echo ">> Jump into Rescue-System..."
      echo "(enter ‘exit’ to leave Shell and open Menu again.)"
      [ -c /dev/console ] || mknod -m 600 /dev/console c 5 1
      [ -c /dev/tty ] || mknod -m 666 /dev/tty c 5 0
      /bin/sh
      ;;
    q|Q)
      echo "Reboot to Orbis OS..."
      exec reboot -f
      ;;
      *)
      echo "Invalid selection."
      ;;
  esac
}

# Hauptschleife
while true; do
  show_menu
  echo "Back to Playstation Bootmenu ..."
  sleep 1
done
# vim: noexpandtab
